### ISSUE TITLE
Unit test failure at org.trustedanalytics.h2oscoringengine.ModelLocatorTest

### ISSUE THREAD

**Issue by daroczig** [trustedanalytics/h2o-scoring-engine-base#6]
I'm trying to build the jar via `mvn clean package`, but I keep getting the below error at 129a8dfbe7ba22e1d69e6c3bfe528a6d0a520dce:

```
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.293 sec - in org.trustedanalytics.h2oscoringengine.integration.tests.H2oScoringEngineControllerTest
Running org.trustedanalytics.h2oscoringengine.ModelLocatorTest
2016-06-22 01:15:08.206  INFO 30084 --- [           main] org.reflections.Reflections              : Reflections took 1780 ms to scan 68 urls, producing 4574 keys and 24010 values 
2016-06-22 01:15:09.511  INFO 30084 --- [           main] org.reflections.Reflections              : Reflections took 1289 ms to scan 66 urls, producing 4572 keys and 23999 values 
2016-06-22 01:15:10.901  INFO 30084 --- [           main] org.reflections.Reflections              : Reflections took 1209 ms to scan 67 urls, producing 4573 keys and 24009 values 
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.653 sec <<< FAILURE! - in org.trustedanalytics.h2oscoringengine.ModelLocatorTest
getModel_ValidClasspathPrepared_ModelInstanceReturned(org.trustedanalytics.h2oscoringengine.ModelLocatorTest)  Time elapsed: 1.967 sec  <<< ERROR!
org.trustedanalytics.h2oscoringengine.h2omodel.ModelNotFoundException: Invalid number of models: 2
    at org.trustedanalytics.h2oscoringengine.h2omodel.ModelLocator.findModel(ModelLocator.java:39)
    at org.trustedanalytics.h2oscoringengine.h2omodel.ModelLocator.getModel(ModelLocator.java:27)
    at org.trustedanalytics.h2oscoringengine.ModelLocatorTest.getModel_ValidClasspathPrepared_ModelInstanceReturned(ModelLocatorTest.java:42)

2016-06-22 01:15:10.906  INFO 30084 --- [       Thread-2] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@3d4e405e: startup date [Wed Jun 22 01:14:58 CEST 2016]; root of context hierarchy

Results :

Tests in error: 
  ModelLocatorTest.getModel_ValidClasspathPrepared_ModelInstanceReturned:42 » ModelNotFound
```

Java version:

```
javac 1.8.0_91
```

Any ideas on this unit test failure? Is there anything I can help with debugging this?

**Comment by dpuzio** [comment]
Hi,
Thank you for pointing this out. 
It is a problem with maven-surefire configuration - by default it reuses one process to execute multiple tests (more on this here: http://maven.apache.org/surefire/maven-surefire-plugin/examples/fork-options-and-parallel-execution.html in Forked Test Execution chapter). Since some of our tests load classes and check the number of them, they can affect each other when executed in the same process. 
I've just pushed a commit that changes maven-surefire configuration.

**Comment by daroczig** [comment]
Thank you very much -- the tests now run without any problem.
